# SPDX-License-Identifier: MPL-2.0
name = "LowLevel"
uuid = "01a11d29-d884-82e8-9db2-8ff667f451ca"
authors = ["Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>"]
version = "0.1.1"
license = "MPL-2.0"

[deps]
AcceleratorGate = "59f742c7-270d-4a76-95d4-a853ae16cc71"
HardwareResilience = "01a11d29-d880-869f-9c60-029824b42355"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
SiliconCore = "01a11d29-d88c-832a-9ded-976af4b7dc75"

[compat]
AcceleratorGate = "0.1"
HardwareResilience = "0.1"
SiliconCore = "0.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
